v-2
ZarinPal/zarinpal-php-sdk pull request #2
Opened 2024-09-25 09:02 UTC by ar4min

2024-09-29 12:16 UTC, MA7 requested changes

2024-09-29 12:16 UTC, MA7 commented on src/Endpoint/PaymentGateway/RequestTypes/ReverseRequest.php
> +        if ($this->merchantId === null || !preg_match('/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/', $this->merchantId)) {
make public function for valid uuid

2024-09-29 12:16 UTC, MA7 commented on src/Endpoint/PaymentGateway/RequestTypes/ReverseRequest.php
> +        if (!preg_match('/^A[0-9a-zA-Z]{35}$/', $this->authority)) {
make public function for valid Authority

2024-09-29 12:16 UTC, MA7 commented on src/Endpoint/PaymentGateway/ResponseTypes/UnverifiedResponse.php
> +            $this->code = 0;
handle this
we don't have 0 response code

2024-09-29 12:16 UTC, MA7 commented on src/Options.php
> +            'base_url' => 'https://payment.zarinpal.com',
add ENV ZARINPAL_MERCHANT_URL

2024-09-29 12:16 UTC, MA7 commented on tests/BaseTestCase.php
> +            'merchant_id' => '25fe4c36-66e4-11e9-a9e4-000c29344814',
use https://fusionauth.io/dev-tools/uuid-generator for generate uuid

2024-09-29 12:16 UTC, MA7 commented on tests/PaymentGateway/PaymentGatewayTest.php
> +                'authority' => 'A00000000000000000000000000123456',
A0000000000000000000000000012b4A6

2024-10-01 12:12 UTC, ar4min commented on examples/Inquiry.php
> +require_once __DIR__ . '/../vendor/autoload.php';
با این مدل کار نکرد..

2024-10-06 13:34 UTC, MA7 requested changes

2024-10-06 13:34 UTC, MA7 commented on src/Endpoint/GraphQL/RefundService.php
> +            throw $e;
$e->?

2024-10-06 13:34 UTC, MA7 commented on src/Endpoint/GraphQL/RefundService.php
> +    private function checkHttpError(ResponseInterface $response): void
dupicate

2024-10-06 13:34 UTC, MA7 commented on src/Endpoint/GraphQL/TransactionService.php
> +                'User-Agent' => sprintf('%sSdk/v.0.1 (php %s)', $this->getClassName(), PHP_VERSION),
make CONST

2024-10-06 13:34 UTC, MA7 commented on src/Endpoint/GraphQL/TransactionService.php
> +        } catch (Exception $e) {
} catch (Exception $e) {
            throw new ResponseException('Request failed: ' . $e->getMessage(), $e->getCode(), null, ['details' => $e->getMessage()]);
        }

2024-10-06 13:34 UTC, MA7 commented on src/Options.php
> +            'base_url' => $this->arrayGet(getenv(), 'ZARINPAL_BASE_URL', 'https://payment.zarinpal.com'),
add .env.sample

2024-10-06 13:34 UTC, MA7 commented on src/Validator.php
> +    public static function validateAmount(int $amount, int $minAmount = 1): void
100 Toman 1000 Rial

2024-10-06 13:34 UTC, MA7 commented on src/Validator.php
> +        if (!preg_match('/^https?:\/\/.*/', $callback_url)) {
http is valid too

2024-10-08 06:31 UTC, merged